# Generated by Django 3.2.25 on 2024-07-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address_L1', models.CharField(max_length=200)),
                ('address_L2', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
            ],
        ),
    ]
